name: Build and push container image

on:
  workflow_dispatch:
    inputs:
      php-run-id:
        description: PHP workflow run ID
        type: number

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    strategy:
      matrix:
        php: ['8.3']
    runs-on: ubuntu-latest
    name: "Build and push ${{ matrix.php }}"
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download PHP artifacts
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ github.event.inputs.php-run-id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        build-args: |
          PHPVERSION: ${{ matrix.php }}
        platforms: linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.php }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
