name: Build PHP

on:
  workflow_dispatch:

env:
  EXTENSIONS: amqp,apcu,ast,bcmath,brotli,calendar,ctype,curl,dom,ds,exif,ffi,fileinfo,filter,gd,gettext,iconv,igbinary,imagick,inotify,intl,ldap,libxml,mbregex,mbstring,memcache,memcached,mongodb,msgpack,mysqli,mysqlnd,opcache,openssl,opentelemetry,parallel,password-argon2,pcntl,pdo,pdo_mysql,pgsql,phar,posix,rdkafka,readline,redis,session,shmop,simplexml,soap,sockets,sodium,sqlite3,swoole,swoole-hook-mysql,swoole-hook-pgsql,swoole-hook-sqlite,tokenizer,xlswriter,xml,xmlreader,xmlwriter,xsl,yaml,zip,zlib,zstd
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        php: ['8.3']
        platform:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    
    runs-on: ${{ matrix.platform.runner }}
    name: "Build ${{ matrix.php }} ${{ matrix.platform.arch }}"
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v4
        with:
          repository: crazywhalecc/static-php-cli

      - name: Update Swoole version to v5.1.7
        run: |
          sed -i '/"swoole": {/,/}/ s/"rev": "[^"]*"/"rev": "v5.1.7"/' config/source.json
          echo "Updated swoole rev to v5.1.7"
          grep -A 5 -B 1 '"swoole"' config/source.json || echo "swoole not found in config file"

      - name: Update MongoDB driver to 1.x versions only
        run: |
          sed -i '/"mongodb": {/,/}/ s/"match": "[^"]*"/"match": "mongodb-1\\\\.[0-9]+\\\\.[0-9]+\\\\.tgz"/' config/source.json
          echo "Updated mongodb match to 1.x versions only"
          grep -A 5 -B 1 '"mongodb"' config/source.json || echo "mongodb not found in config file"

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: pecl, composer
          extensions: curl, openssl, mbstring
          ini-values: memory_limit=-1
        env:
          phpts: nts

      - uses: actions/cache@v4
        with:
          path: downloads
          key: php-dependencies
      - run: composer install --prefer-dist --no-dev
      - run: ./bin/spc-alpine-docker download --with-php=${{ matrix.php }} --for-extensions=${{ env.EXTENSIONS }}
      - run: ./bin/spc-alpine-docker build ${{ env.EXTENSIONS }} --enable-zts --build-cli
      
      - uses: actions/upload-artifact@v4
        with:
          name: php${{ matrix.php }}-${{ matrix.platform.arch }}
          path: buildroot/bin/php
